version: "3.9"

services:
  bank_phpfpm:
    build:
      context: ./config/php-fpm
      dockerfile: Dockerfile
    container_name: i_phpfpm
    restart: unless-stopped
    volumes:
      - ./src/banking:/var/www/banking
      - ./config/php-fpm/php.ini:/usr/local/etc/php/php.ini

  local_bank_db: 
    image: mysql:8
    container_name: i_local_mysql
    volumes: 
      - ./local-data/mysql/banking_db:/var/lib/local-data/mysql 
    restart: always 
    ports: 
      - "3306:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=banking_db
  remote_bank_db: 
    image: mysql:8
    container_name: i_remote_mysql
    volumes: 
      - ./remote-data/mysql/banking_db:/var/lib/remote-data/mysql 
    restart: always 
    ports: 
      - "3307:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=banking_db
  bank_app:
    image: nginx:alpine
    container_name: i_banking
    volumes:
      - ./src/banking:/var/www/banking
      - ./config/nginx/banking.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
